name: AST Javascript wrapper CI

on: [pull_request]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Code Linting
        run: npm run lint
      - run: npm run build --if-present
      - name: Run tests
        env:
          CX_CLIENT_ID: ${{ secrets.CX_CLIENT_ID}}
          CX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET}}
          CX_BASE_URI: ${{ secrets.CX_BASE_URI }}
          CX_TENANT: ${{ secrets.CX_TENANT }}
          CX_SCANID: ${{ secrets.SCANID }}
          CX_APIKEY: ${{ secrets.CX_APIKEY }}
        run: npm test