# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration Tests

on:
  push:
    branches: [ master,change-to-typescript ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy executable
      run: cp ./src/main/resources/cx-linux /tmp/
    - name: Permissions to executable
      run: sudo chmod 777 /tmp/cx-linux
    - name: Jest Test cases
      env:
        CX_CLIENT_ID: ${{ secrets.CLIENT_ID}}
        CX_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET}}
        CX_BASE_URI: ${{ secrets.BASE_URI }}
        PATH_TO_EXECUTABLE: /tmp/cx-linux
      run: npm ci | npm run build --if-present | npm test
