name: Manual Tag Creation

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true

jobs:
  tag-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Tag
        run: |
          echo ${{ github.event.inputs.tag }}
          echo "NEXT_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
      - name: Update version
        run: |
          npm version ${{ env.RELEASE_VERSION }}
          git push origin ${{ env.RELEASE_VERSION }}
