name: Manual Tag Creation

on:
  workflow_dispatch:

jobs:
  tag-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Update version
        run: |
          npm version patch
          git push && git push --tags
